#No terminal executar "rake teste" para rodar essa tarefa
# Quando é necessário recriar a massa de testes utilizar o rake

require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :teste do
    puts "Executando uma tarefa de teste"

end

#massa de teste pois no cucumber o before executa mais de uma vez, e dessa forma ele executa 1 unica vez antes dos testes
task :local_seeds do
    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

    users = [
        { name: "Roberto Carlos", email: "betao@yahoo.com", password: to_md5("pwd123") },
        { name: "Fernanda R", email: "fernandaR@gmail.com", password: to_md5("pwd123") },
        { name: "Spider", email: "spider@hotmail.com", password: to_md5("pwd123") },
        { name: "João Anunciante", email: "joao@anunciante.com", password: to_md5("pwd123") },
        { name: "Maria Locataria", email: "maria@locataria.com", password: to_md5("pwd123") },
      ]
  
      MongoDB.new.drop_danger
      MongoDB.new.insert_users(users)

      # rodar o cucumber
      sh "cucumber"
end

# task :homolog_seeds do
#     CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/homolog.yml}"))

#     users = [
#         { name: "Roberto Carlos", email: "betao@yahoo.com", password: to_md5("pwd123") },
#         { name: "Fernanda R", email: "fernandaR@gmail.com", password: to_md5("pwd123") },
#       ]
  
#       MongoDB.new.drop_danger
#       MongoDB.new.insert_users(users)
# end